#!/usr/bin/env python3
"""
Create full Prometheus config files based on sources that might be editable by end users.
"""
import argparse
import glob
import pathlib

from prometheus_configurator.config import load_config_files
from prometheus_configurator.outputs import create_output
from prometheus_configurator.prometheus import ConfigFileCreator


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config', help="Config file(s) used to instruct prometheus-configurator what to do.", action='append')
    args = parser.parse_args()

    config_files = []
    for config_glob in args.config:
        for file in glob.glob(config_glob):
            config_files.append(pathlib.Path(file))

    own_config = load_config_files(config_files)

    creator = ConfigFileCreator(own_config)

    # TODO: shard projects across multiple prometheus instances?
    projects = creator.get_defined_projects()

    for output_config in own_config.get("outputs"):
        output = create_output(output_config, own_config)
        output.write(creator, projects)


if __name__ == '__main__':
    main()
